name: test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
            bash main.sh test

  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        run: |
            shellcheck main.sh